export default [
  { text: "// Binary Search Tree implementation", type: "comment" },
  { text: "import java.util.LinkedList;", type: "import" },
  { text: "import java.util.Queue;", type: "import" },
  { text: "", type: "blank" },
  { text: "public class BinarySearchTree {", type: "code" },
  { text: "", type: "blank" },
  { text: "    private static class Node {", type: "code" },
  { text: "        int val;", type: "code" },
  { text: "        Node left, right;", type: "code" },
  { text: "        Node(int v) { val = v; }", type: "code" },
  { text: "    }", type: "code" },
  { text: "", type: "blank" },
  { text: "    private Node root;", type: "code" },
  { text: "", type: "blank" },
  { text: "    public void insert(int val) {", type: "code" },
  { text: "        root = insertRec(root, val);", type: "code" },
  { text: "    }", type: "code" },
  { text: "", type: "blank" },
  { text: "    private Node insertRec(Node node, int val) {", type: "code" },
  { text: "        if (node == null) return new Node(val);", type: "code" },
  { text: "        if (val < node.val) node.left  = insertRec(node.left,  val);", type: "code" },
  { text: "        else if (val > node.val) node.right = insertRec(node.right, val);", type: "code" },
  { text: "        return node;", type: "code" },
  { text: "    }", type: "code" },
  { text: "", type: "blank" },
  { text: "    public boolean search(int val) {", type: "code" },
  { text: "        Node cur = root;", type: "code" },
  { text: "        while (cur != null) {", type: "code" },
  { text: "            if (val == cur.val) return true;", type: "code" },
  { text: "            cur = val < cur.val ? cur.left : cur.right;", type: "code" },
  { text: "        }", type: "code" },
  { text: "        return false;", type: "code" },
  { text: "    }", type: "code" },
  { text: "", type: "blank" },
  { text: "    public void inOrder(Node n) {", type: "code" },
  { text: "        if (n == null) return;", type: "code" },
  { text: "        inOrder(n.left);", type: "code" },
  { text: '        System.out.print(n.val + " ");', type: "code" },
  { text: "        inOrder(n.right);", type: "code" },
  { text: "    }", type: "code" },
  { text: "", type: "blank" },
  { text: "    public static void main(String[] args) {", type: "code" },
  { text: "        BinarySearchTree bst = new BinarySearchTree();", type: "code" },
  { text: "        int[] data = {50, 30, 70, 20, 40, 60, 80};", type: "code" },
  { text: "        for (int d : data) bst.insert(d);", type: "code" },
  { text: "        bst.inOrder(bst.root);", type: "code" },
  { text: "        System.out.println();", type: "code" },
  { text: '        System.out.println("Found 40: " + bst.search(40));', type: "code" },
  { text: "    }", type: "code" },
  { text: "}", type: "code" },
]